# Generated by Django 5.1.4 on 2025-01-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='hazard',
            old_name='hazard_category',
            new_name='HazardCategory',
        ),
        migrations.RenameField(
            model_name='hazard',
            old_name='submitted_at',
            new_name='submittedAt',
        ),
        migrations.RemoveField(
            model_name='hazard',
            name='reported_by',
        ),
        migrations.AddField(
            model_name='hazard',
            name='reportedBy',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
    ]
